version: '3.7'

services:
  broker:
    image: nats-streaming:0.20-alpine
    command: -cid broker
    ports:
      - 4222:4222

  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./node_modules
      - ./:/usr/src/app
    depends_on:
      - broker
      - mongo
